name: Live Deployment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.1'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Enable Maintenance Mode (Upload Maintenance PHP)
      uses: bayssmekanique/action-simple-file-upload@v2
      with:
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        host: ${{ secrets.FTP_SERVER }}
        src: public/maintenance.php
        dest: ${{ secrets.BASE_PATH }}/public/index.php
        secure: true
        verbose: true

    - name: Install Composer
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev --optimize-autoloader

    - name: Clear Cache, Install Assets
      run: |
        php bin/console cache:clear --no-warmup
        php bin/console assets:install

    - name: Use Node.js 18.16.1
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.1

    - name: Build Encore/NPM
      run: |
        npm cache clean --force
        npm install --force
        npm run build

    - name: ðŸ“‚ Deploy Source Files # Deploys /src /bin /config /sync-state and ./ 
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftp
          server-dir: ${{ secrets.BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.main.json
          exclude: |
            **/.git*/**
            **/.git*
            **/.git/**
            **/.github/**
            **/assets/**
            **/migrations/**
            **/node_modules/**
            **/templates/**
            **/translations/**
            **/public/**
            **/tests/**
            **/var/**
            **/vendor/**
            **/.env.local
            **/.env.test
            **/.git*
            **/compose.override.yaml
            **/compose.yaml
            **/install.bat
            **/package-lock.json
            **/package.json
            **/phpunit.xml.dist
            **/todo.md
            **/update.bat
            **/webpack.config.js
            **/build.bat

    - name: ðŸ“‚ Deploy Templates # Deploys /templates /translations
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftp
          server-dir: ${{ secrets.BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.templates.json
          exclude: |
            **/.git*/**
            **/.git*
            **/.git/**
            **/.github/**
            **/assets/**
            **/migrations/**
            **/node_modules/**
            **/src/**
            **/bin/**
            **/config/**
            **/sync-state/**
            **/public/**
            **/tests/**
            **/var/**
            **/vendor/**
            **/.env.local
            **/.env.test
            **/.git*
            **/compose.override.yaml
            **/compose.yaml
            **/install.bat
            **/package-lock.json
            **/package.json
            **/phpunit.xml.dist
            **/todo.md
            **/update.bat
            **/webpack.config.js
            **/.env
            **/.env.local.php
            **/composer.json
            **/composer.lock
            **/symfony.lock
            **/index.php
            **/build.bat
 
    - name: ðŸ“‚ Deploy Assets # Deploys /public
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftp
          server-dir: ${{ secrets.BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.assets.json
          exclude: |
            **/.git*/**
            **/.git*
            **/.git/**
            **/.github/**
            **/assets/**
            **/migrations/**
            **/node_modules/**
            **/sync-state/**
            **/tests/**
            **/var/**
            **/config/**
            **/vendor/**
            **/src/**
            **/bin/**
            **/templates/**
            **/translations/**
            **/.env.local
            **/.env.test
            **/.git*
            **/compose.override.yaml
            **/compose.yaml
            **/install.bat
            **/package-lock.json
            **/package.json
            **/phpunit.xml.dist
            **/todo.md
            **/update.bat
            **/webpack.config.js
            **/.env
            **/.env.local.php
            **/composer.json
            **/composer.lock
            **/symfony.lock
            **/index.php
            **/build.bat

    - name: ðŸ“‚ Deploy Vendor Files # Deploys /vendor
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftp
          server-dir: ${{ secrets.BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.vendor.json
          exclude: |
            **/.git*/**
            **/.git*
            **/.git/**
            **/.github/**
            **/assets/**
            **/migrations/**
            **/node_modules/**
            **/config/**
            **/public/**
            **/sync-state/**
            **/templates/**
            **/translations/**
            **/tests/**
            **/var/**
            **/src/**
            **/bin/**
            **/.env.local
            **/.env.test
            **/.git*
            **/compose.override.yaml
            **/compose.yaml
            **/install.bat
            **/package-lock.json
            **/package.json
            **/phpunit.xml.dist
            **/todo.md
            **/update.bat
            **/webpack.config.js
            **/.env
            **/.env.local.php
            **/composer.json
            **/composer.lock
            **/symfony.lock
            **/build.bat

    - name: Create Empty Directory
      run: mkdir .empty

    - name: ðŸ“‚ Clear Cache # Clears Cache
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: .empty/
          protocol: ftp
          server-dir: ${{ secrets.BASE_PATH }}/var/cache/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate	: true
          dry-run: false

    - name: Disable Maintenance Mode (Upload Public Index PHP)
      uses: bayssmekanique/action-simple-file-upload@v2
      with:
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        host: ${{ secrets.FTP_SERVER }}
        src: public/index.php
        dest: ${{ secrets.BASE_PATH }}/public/index.php
        secure: true
        verbose: true